name: Deployment

on:
  schedule:
    - cron: '0  8,14,19  *  *  *'
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update planet
        run: |
          ./update.sh -g
