name: Deployment

on:
  schedule:
    - cron: '0  8  *  *  *'
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Update planet
        run: |
          ./update.sh -g
